### PR TITLE
A code review preparation for the Responsive Design Project, The Next Web...

### PR DESCRIPTION
**Pull request by jamezjaz**
**The Responsive Design Project, The Next Web**

- The project has both the top and bottom navigation bars.

- It has a search icon.

- It has a harmburger menu icon which only shows when the viewport is less than 768px.

- It has different sections and articles aligned with grids and flex boxes.

- It's responsive on both 1024px and 768px viewports.

- It has both top footer and bottom footer.

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Comment by jamezjaz** [comment]
Okay, I’m waiting

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Good job Team 👍👍👏

**Your code looks clean and efficient with no listing or validating issues@jamezjaz  and @Genius8 👌**

There are however a few issues that need to be fixed before proceeding, kindly read through and apply the fixes accordingly👇:

- [ ] Required - Kindly add a logo to the top navbar as seen when scrolled, simply append a logo to it.
**This is yours👇[Screenshot]**
ice_screenshot_20200330-142819

**This is the way it should be👇[Screenshot]**
ice_screenshot_20200330-144406

- [ ] Required - The top three article sections don't look like the original webpage does. There is a background gradient directly behind the logo in the largest of these articles by the left. Also, note that this gradient disappears on a tablet screen size.
**This is yours👇[Screenshot]**
ice_screenshot_20200330-143109

**This is the way the original webpage looks👇[screenshot]**
ice_screenshot_20200330-143021

**There are other differences if you observe carefully between yours and the original, kindly take note of these and fix them.**

- [ ] **REQUIRED** Also please all sections have an issue of responsiveness. Particularly with the fact that some sections to the left seem to be cut off when the webpage is shrunk continuously to small screen-size Note these differences in the table below:👇

Your Webpage |  ORIGINAL WEBPAGE
----------------- | ------------------
ice_screenshot_20200330-143109 | ice_screenshot_20200330-145241
------------------ | -------------------
ice_screenshot_20200330-142730 | ice_screenshot_20200330-145314
----------------------------- | ----------------
ice_screenshot_20200330-143308 | ice_screenshot_20200330-145326
-------------- | -------------------

- [ ] Required - Also kindly use the right colors for the icons in your footer and the `Latest funding rounds on index.co` section.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by jamezjaz** [comment]
The logo disappears when the viewport is above 1024px and it's also like that on the main page.
Screenshots below:
Nav-bar with logo, viewport below 1024 px
Nav-bar without logo, viewport above 1024 px

**Comment by davidmrtz-dev** [comment]
## Hi Team. 👨‍🚀  
### Very good job so far.
You did a great job implementing the changes required by the previous TSE.
However, the following issues need to be implemented/fixed to consider this project as approved  👨‍💻  ⬇️ 

****
- [ ] Search and hamburger menu icons.

There's is an issue on the 'md' size with the search and hamburger icons.
As you can notice in the images below, your search button is pushed all the way to the right and there's also no hamburger icon like in the original page in 'md' size, please add the menu icon and fix the search icon position.
You can achieve add the hamburger icon only in the size 'md' and below using media queries.
How it looks now. ⬇️ 

Screen Shot 2020-03-31 at 9 14 27 PM

The example on which the project is based. ⬇️ 

Screen Shot 2020-03-31 at 9 14 43 PM

****
- [ ]  Pull request.

Please edit the pull request and add a short description of what you did in this project.
You can add 3 or 4 points in a list.
You can find more info here ➡️ ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
****
- [ ] Latest news and Latest deals on 'sm' size.

We also have an issue with the 'sm' size.
Please check in detail the image below and follow it to position the required elements.
❗️ Remember, we are making a clone of the page, so we must make it as similar as possible to the original.

How it looks now. ⬇️ 

Screen Shot 2020-03-31 at 9 19 43 PM

The example on which the project is based. ⬇️ 

Screen Shot 2020-03-31 at 9 20 23 PM

The same with Latest deals section.

How it looks now. ⬇️ 

Screen Shot 2020-03-31 at 9 23 06 PM


The example on which the project is based. ⬇️ 

Screen Shot 2020-03-31 at 9 23 11 PM
****

### **Please kindly make the changes required and submit for re-review once you are ready!** 🙏 

****

### Status: Changes required. ♻️  👀 
****

Happy coding! 😄 💻  


**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

**Comment by jamezjaz** [comment]
**The Responsive Design Project, The Next Web**
1. The project has both the top and bottom navigation bars. 
2. It has a search icon. 
3. It has a harmburger menu icon which only shows when the viewport is less than 768px. 
4. It has different sections and articles aligned with grids and flex boxes. 
5. It's responsive on both 1024px and 768px viewports. 
6. It has both top footer and bottom footer.

**Review by mikenath223 — APPROVED** [review]
HI TEAM 👋

### CONGRATULATIONS  @jamezjaz and @Genius8 👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**

I am approving this project because I trust you will fix this issue before merging.
Kindly fix this:👇

- [ ] - Properly align the date element beside the article logo, on a large screen size, as it is overlapped by the logo image. {Screenshot]👇
ice_screenshot_20200402-003210


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Comment by jamezjaz** [comment]
Thank you 😊
Trust me, I’ll definitely align the date element.

**Comment by jamezjaz** [comment]
Done!
I've re-aligned the date element.
*@mikenath223, *I appreciate your efforts and that's of other TSEs.
Thank you.

**Pull request merged**
